-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 15:27:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tutor` (
  `TutorID` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TutorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tutee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tutee` (
  `TuteeID` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TuteeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `PID` INT NOT NULL,
  `Tutor` INT NOT NULL,
  `Subject` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  PRIMARY KEY (`PID`),
  INDEX `Post Tutor_idx` (`Tutor` ASC),
  CONSTRAINT `Tutor`
    FOREIGN KEY (`Tutor`)
    REFERENCES `mydb`.`Tutor` (`TutorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Application` (
  `AppID` INT NOT NULL,
  `PostID` INT NOT NULL,
  `TuteeID` INT NOT NULL,
  `Subject` INT NULL,
  `App bool` VARCHAR(45) NULL,
  `Message` VARCHAR(100) NULL,
  PRIMARY KEY (`AppID`),
  INDEX `Tutee ID_idx` (`TuteeID` ASC),
  INDEX `Post ID_idx` (`PostID` ASC),
  CONSTRAINT `PostID`
    FOREIGN KEY (`PostID`)
    REFERENCES `mydb`.`Post` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TuteeID`
    FOREIGN KEY (`TuteeID`)
    REFERENCES `mydb`.`Tutee` (`TuteeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `RID` INT NOT NULL,
  `RTutorID` INT NOT NULL,
  `Score` INT NOT NULL,
  `RTuteeID` INT NOT NULL,
  PRIMARY KEY (`RID`),
  INDEX `Tutor ID_idx` (`RTutorID` ASC) ,
  INDEX `TuteeID_idx` (`RTuteeID` ASC) ,
  CONSTRAINT `RTutorid`
    FOREIGN KEY (`RTutorID`)
    REFERENCES `mydb`.`Tutor` (`TutorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RTuteeid`
    FOREIGN KEY (`RTuteeID`)
    REFERENCES `mydb`.`Tutee` (`TuteeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
